name             'et_pipeline'
maintainer       'EverTrue, Inc.'
maintainer_email 'devops@evertrue.com'
license          'Apache 2.0'
description      'Installs/Configures et_pipeline'
long_description 'Installs/Configures et_pipeline'
version          '1.0.2'

depends 'pipeline'
depends 'ssh_known_hosts'
